insert into user (first_name, last_name, email) values ('Ivan','Ivanov', 'ivan@yandex.ru');
insert into user (first_name, last_name, email) values ('Petr', 'Petrov', 'pvan@yandex.ru');
insert into user (first_name, last_name, email) values ('Sidor','Sidorov', 'sidor@yandex.ru');
insert into user (first_name, last_name, email) values ('Marfa', 'Marfova', 'marfa@yandex.ru');
insert into user (first_name, last_name, email) values ('Alex', 'Putin', 'putin@yandex.ru');
insert into user (first_name, last_name, email) values ('Михаил', 'Медведев', 'medved@yandex.ru');
insert into user (first_name, last_name, email) values ('Ольга','Яровая', 'yarov@yandex.ru');
insert into user (first_name, last_name, email) values ('Алексей','Березуцкий', 'berez@yandex.ru');
insert into user (first_name, last_name, email) values ('Иван', 'Пинский', 'pin@yandex.ru');
insert into user (first_name, last_name, email) values ('Святогор','Борисов', 'boris@yandex.ru');
insert into user (first_name, last_name, email) values ('Николай','Кобзон', 'kobz@yandex.ru');
insert into user (first_name, last_name, email) values ('Никодим','Николаев', 'nik@yandex.ru');
insert into user (first_name, last_name, email) values ('Вячеслав','Чилингаров', 'chil@yandex.ru');
insert into user (first_name, last_name, email) values ('Станислав','Шойгу', 'shoy@yandex.ru');
insert into user (first_name, last_name, email) values ('Игорь','Тулеев', 'tul@yandex.ru');
insert into user (first_name, last_name, email) values ('Валентин','Евтушенко', 'evt@yandex.ru');
insert into user (first_name, last_name, email) values ('Петр','Белеков', 'bel@yandex.ru');
insert into user (first_name, last_name, email) values ('Михаил','Мельник', 'mel@yandex.ru');
insert into user (first_name, last_name, email) values ('Константин','Герасименко', 'ger@yandex.ru');
insert into user (first_name, last_name, email) values ('Олег','Косяненко', 'kos@yandex.ru');
insert into user (first_name, last_name, email) values ('Сергей','Елыкомов', 'el@yandex.ru');